name: Build OpenCord

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:

    strategy:
      fail-fast: false
      matrix:
        platform:
          - windows-latest
          - ubuntu-latest
          - macos-latest

    runs-on: ${{ matrix.platform }}

    steps:

      - name: Télécharger le code
        uses: actions/checkout@v4


      - name: Installer Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22


      - name: Installer Rust
        uses: dtolnay/rust-toolchain@stable


      - name: Installer les dépendances
        run: npm install


      - name: Build OpenCord
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        with:
          releaseName: "OpenCord Release"
          releaseDraft: false
          prerelease: false
